version: '3.0'

services:
  grafana:
    container_name: 'serrrios-statusoverview-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.4.7}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/serrrios-statusoverview-panel
      - ./provisioning:/etc/grafana/provisioning
