name: Build and Sign Plugin

on:
  push:
    tags:
      - 'v*.*.*' # Run workflow on version tags, e.g. v1.0.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build plugin
      run: npm run build
    
    - name: Sign plugin
      uses: grafana/plugin-actions/sign-plugin@master
      with:
        plugin-id: ${{ secrets.GRAFANA_PLUGIN_ID }}
        plugin-path: ./dist
      env:
        GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
    
    - name: Setup plugin packaging
      run: |
        mkdir -p package/${{ secrets.GRAFANA_PLUGIN_ID }}
        cp -r dist/* package/${{ secrets.GRAFANA_PLUGIN_ID }}
    
    - name: Package plugin
      working-directory: ./package
      run: |
        zip -r ${{ secrets.GRAFANA_PLUGIN_ID }}.zip ${{ secrets.GRAFANA_PLUGIN_ID }}
        mv ${{ secrets.GRAFANA_PLUGIN_ID }}.zip ${{ secrets.GRAFANA_PLUGIN_ID }}-$(echo ${{ github.ref_name }} | cut -c 2-).zip
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: ./package/${{ secrets.GRAFANA_PLUGIN_ID }}-*.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
